# 是否开启请求日志
requestLog: true
# 是否调试模式
debug: true
# 日志级别: error, warning, info, debug
log_level: debug
# 临时目录
tmpDir: ./tmp
# 日志目录
logDir: ./logs
# 日志写入间隔（毫秒）
logWriteInterval: 200
# 日志文件有效期（毫秒）
logFileExpires: 2626560000
# 公共目录
publicDir: ./public
# 临时文件有效期（毫秒）
tmpFileExpires: 86400000
